title: Bufete PAYES Y ASOCIADOS
email: mpayesp2@miumg.edu.dt
description: >- 
  Catálogo y misión de nuestro Bufete.
baseurl: "" 
url: "https://github.com/Mpayes2/prueba.git"
theme: minima
<link rel="icon" href="/favicon.ico">
